// Copyright (C) 2016  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel MegaCore Function License Agreement, or other 
// applicable license agreement, including, without limitation, 
// that your use is for the sole purpose of programming logic 
// devices manufactured by Intel and sold by Intel or its 
// authorized distributors.  Please refer to the applicable 
// agreement for further details.


// Generated by Quartus Prime Version 16.1 (Build Build 196 10/24/2016)
// Created on Thu Mar 16 04:08:59 2017

SAT_accelerator SAT_accelerator_inst
(
	.outCNF(outCNF_sig) ,	// output  outCNF_sig
	.clk(clk_sig) ,	// input  clk_sig
	.resetClause(resetClause_sig) ,	// input  resetClause_sig
	.negCtrl(negCtrl_sig) ,	// input  negCtrl_sig
	.enableClause(enableClause_sig) ,	// input  enableClause_sig
	.varPos(varPos_sig) ,	// input [4:0] varPos_sig
	.resetCNF(resetCNF_sig) ,	// input  resetCNF_sig
	.enableCNF(enableCNF_sig) 	// input  enableCNF_sig
);

